apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vitubot
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/revision-history-limit: "3"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  rules:
  - host: k3s.quokka.ninja
    http:
      paths:
      - path: /vitubot
        pathType: Prefix
        backend:
          service:
            name: vitubot
            port:
              number: 8000
  tls:
    - hosts:
      - k3s.quokka.ninja
      secretName: k3s.quokka.ninja